/* Drop Tables */

DROP TABLE REPLY CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE MESSAGE CASCADE CONSTRAINTS;
DROP TABLE GAMES CASCADE CONSTRAINTS;
DROP TABLE GROUND_REVIEW CASCADE CONSTRAINTS;
DROP TABLE GROUNDS CASCADE CONSTRAINTS;
DROP TABLE MATCHING CASCADE CONSTRAINTS;
DROP TABLE PLAYER CASCADE CONSTRAINTS;
DROP TABLE RECORD CASCADE CONSTRAINTS;
DROP TABLE TEAM CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;


select * from message;

/* Create Sequences */

CREATE SEQUENCE SEQ_GROUND INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_MATCHING INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_RECORD INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_BOARD INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_REPLY INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_GROUND_REVIEW INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_MESSAGE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TEAM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_GAMES INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_NOTICE INCREMENT BY 1 START WITH 1;


--drop sequence seq_message;

/*drop seq*/

DROP SEQUENCE SEQ_GROUND;
DROP SEQUENCE SEQ_MATCHING;
DROP SEQUENCE SEQ_RECORD;
DROP SEQUENCE SEQ_BOARD;
DROP SEQUENCE SEQ_REPLY;
DROP SEQUENCE SEQ_GROUND_REVIEW;
DROP SEQUENCE SEQ_MESSAGE;
DROP SEQUENCE SEQ_TEAM;
DROP SEQUENCE SEQ_GAMES;
DROP SEQUENCE SEQ_NOTICE;



/* Create Tables */


CREATE TABLE RECORD(
   RECORD_ID number(5) primary key,
   FB_TOTAL number DEFAULT 0,
   FB_WIN number DEFAULT 0,
   FB_DRAW number DEFAULT 0,
   BB_TOTAL number DEFAULT 0,
   BB_WIN number DEFAULT 0,
   BB_DRAW number DEFAULT 0,
   PP_TOTAL number DEFAULT 0,
   PP_WIN number DEFAULT 0,
   PP__DRAW number DEFAULT 0,
   BL_TOTAL number DEFAULT 0,
   BL_WIN number DEFAULT 0,
   BL_DRAW number DEFAULT 0
);

CREATE TABLE TEAM(
   -- 팀ID
   TEAM_ID number primary key,
   -- 팀이름
   TEAM_NAME varchar2(500 char) NOT NULL,
   TEAM_LEADER varchar2(100 char) NOT NULL,
   -- 팀승점
   TEAM_SCORE number(5) default 0 NOT NULL,
   -- 팀매너점수
   TEAM_MANNER number(10) default 100 NOT NULL,
   -- 팀종목
   TEAM_GAMETYPE varchar2(10 char) NOT NULL,
   TEAM_TOTALGAME number,
   TEAM_WINGAME number,
   TEAM_DRAW number,
   -- 팀 모집여부
   TEAM_OPEN number(1)
);


CREATE TABLE PLAYER(
   USER_ID varchar2(100) primary key,
   USER_NAME varchar2(100) NOT NULL,
   USER_PW varchar2(30) NOT NULL,
   USER_LOCATION varchar2(20) NOT NULL,
   USER_PHONE varchar2(15) NOT NULL,
   RECORD_ID number(5) NOT NULL ,
   TEAM1 number,
   TEAM1_FLAG number(1),
   TEAM2 number,
   TEAM2_FLAG number(1),
   PP_SCORE number default 0,
   BL_SCORE number default 0 ,
   savefilename varchar2(100),
   USER_MANNER number default 100,
   constraint FK_PLAYER_RECORD_ID foreign key(RECORD_ID)
   references RECORD(RECORD_ID),
   constraint FK_PLAYER_TEAM1 foreign key(TEAM1)
   references TEAM(TEAM_ID),
   constraint FK_PLAYER_TEAM2 foreign key(TEAM1)
   references TEAM(TEAM_ID)
);

--alter table player add savefilename varchar2(100);


CREATE TABLE MATCHING(
   -- 매칭_ID
   MATCHING_ID number(10) primary key,
   PLAYER varchar2(100 char) NOT NULL,
   SCORE number,
   -- 운동종류
   GAME_TYPE varchar2(10 char) NOT NULL,
   -- 경기일
   GAME_DATE date NOT NULL,
   -- 경기시간대
   GAME_TIME number(2),
   -- 경기장예약여부
   GROUND_HOLD number(1),
   -- 경기지역
   LATITUDE varchar2(100 char) NOT NULL,--위도
   LONGITUDE varchar2(100 char) NOT NULL,--경도
   -- 이 시간까지 매칭안되면 강제매칭 시작하는 시간
   MATCHING_TIME date NOT NULL
);



CREATE TABLE BOARD(
   BOARDNUM number primary key,
   TITLE varchar2(500 char) NOT NULL,
   CONTENT varchar2(4000 char) NOT NULL,
   -- 회원ID
   USER_ID varchar2(100 char) NOT NULL,
   INPUTDATE date NOT NULL,
   CATEGORY varchar2(100 char) NOT NULL,
   constraint FK_BOARD_USER_ID foreign key(USER_ID)
   references PLAYER(USER_ID)
);


CREATE TABLE REPLY
(
   REPLYNUM number primary key,
   BOARDNUM number NOT NULL,
   -- 회원ID
   USER_ID varchar2(100 char) NOT NULL,
   CONTENT varchar2(2000),
   INPUTDATE date,
   constraint FK_REPLY_USER_ID foreign key(USER_ID)
   references PLAYER(USER_ID),
   constraint FK_REPLY_BOARDNUM foreign key(BOARDNUM)
   references BOARD(BOARDNUM)
);


CREATE TABLE GAMES(
   -- 경기ID
   GAME_ID number(10) primary key,
   -- 경기종류
   GAME_TYPE varchar2(15) NOT NULL,
   --경기하는 시간
   GAME_TIME number NOT NULL,
   PLAYER1 varchar2(100 char) NOT NULL,
   P1_LATITUDE varchar2(20 char),--위도
   P1_LONGITUDE varchar2(20 char),--경도
   PLAYER2 varchar2(100 char) NOT NULL,
   P2_LATITUDE varchar2(20 char),--위도
   P2_LONGITUDE varchar2(20 char),--경도
   -- 승자ID
   WINNER_ID varchar2(20 char),
   -- 경기_무승부
   GAME_DRAW number(1),
   -- 경기_무효
   GAME_INVALIDITY number(1),
   -- 경기장ID
   GROUND_ID number(10),
   -- 결과입력 인증키(유저1)
   PLAYER1_KEY varchar2(6 char),
   -- 결과입력 인증키(유저2)
   PLAYER2_KEY varchar2(6 char)
);


CREATE TABLE GROUNDS
(
   -- 경기장ID
   GROUND_ID number(20) primary key,
   -- 경기장_이름
   GROUND_NAME varchar2(50) NOT NULL,
   -- 경기장_전화번호
   GROUND_PHONE varchar2(38 char) NOT NULL,
   -- 경기장_주소
   GROUND_ADDRESS varchar2(50 char) NOT NULL,
   GROUND_LATITUDE varchar2(30 char),--위도백윤석이오류냄
   GROUND_LONGITUDE varchar2(30 char),--경도
   GROUND_TYPE number(2) not null
);


CREATE TABLE GROUND_REVIEW(
   RVNUM number primary key,
   -- 경기장ID
   GROUND_ID number(10) NOT NULL,
   CONTENT varchar2(500 char) NOT NULL,
   -- 회원ID
   USER_ID varchar2(100 char) NOT NULL,
   constraint FK_GROUND_REVIEW_GROUND_ID foreign key(GROUND_ID)
   references GROUNDS(GROUND_ID)
);

CREATE TABLE MESSAGE(
   MSGNUM number primary key,
   CONTENT varchar2(2000 char),
   -- 회원ID
   USER_ID varchar2(100 char) NOT NULL,
   -- 경기ID
   GAME_ID number(10) NOT NULL,
   INPUTDATE date
);

--알림용?
CREATE TABLE NOTICE(
    NOTICENUM number primary key,
    USER_ID varchar2(100 char) NOT NULL,
    GAME_ID number(10),
    N_TYPE number(1) not null,   --1:경기 성사 2:매칭 실패 3:수락요청(예정)
    constraint FK_NOTICE_USER_ID foreign key(USER_ID)
      references PLAYER(USER_ID)
);



/* Comments */

COMMENT ON COLUMN BOARD.USER_ID IS '회원ID';
COMMENT ON COLUMN GAMES.GAME_ID IS '경기ID';
COMMENT ON COLUMN GAMES.GAME_TYPE IS '경기종류';
COMMENT ON COLUMN GAMES.WINNER_ID IS '승자ID';
COMMENT ON COLUMN GAMES.GAME_DRAW IS '경기_무승부';
COMMENT ON COLUMN GAMES.GAME_INVALIDITY IS '경기_무효';
COMMENT ON COLUMN GAMES.GROUND_ID IS '경기장ID';
COMMENT ON COLUMN GAMES.PLAYER1_KEY IS '결과입력 인증키(유저1)';
COMMENT ON COLUMN GAMES.PLAYER2_KEY IS '결과입력 인증키(유저2)';
COMMENT ON COLUMN GROUNDS.GROUND_ID IS '경기장ID';
COMMENT ON COLUMN GROUNDS.LOCATION IS '경기장_지역';
COMMENT ON COLUMN GROUNDS.GROUND_NAME IS '경기장_이름';
COMMENT ON COLUMN GROUNDS.GROUND_OWN IS '보유경기구장_수';
COMMENT ON COLUMN GROUNDS.GROUND_PHONE IS '경기장_전화번호';
COMMENT ON COLUMN GROUNDS.GROUND_ADDRESS IS '경기장_주소';
COMMENT ON COLUMN GROUND_REVIEW.GROUND_ID IS '경기장ID';
COMMENT ON COLUMN GROUND_REVIEW.USER_ID IS '회원ID';
COMMENT ON COLUMN MATCHING.MATCHING_ID IS '매칭_ID';
COMMENT ON COLUMN MATCHING.GAME_TYPE IS '운동종류';
COMMENT ON COLUMN MATCHING.GAME_DATE IS '경기일';
COMMENT ON COLUMN MATCHING.GAME_TIME IS '경기시간대';
COMMENT ON COLUMN MATCHING.GROUND_HOLD IS '경기장예약여부';
COMMENT ON COLUMN MATCHING.LOCATION IS '경기지역';
COMMENT ON COLUMN MATCHING.MATCHING_STARTTIME IS '매칭시작시간';
COMMENT ON COLUMN MESSAGE.USER_ID IS '회원ID';
COMMENT ON COLUMN MESSAGE.GAME_ID IS '경기ID';
COMMENT ON COLUMN PLAYER.USER_ID IS '회원ID';
COMMENT ON COLUMN PLAYER.USER_NAME IS '회원이름';
COMMENT ON COLUMN PLAYER.USER_PW IS '회원비밀번호';
COMMENT ON COLUMN PLAYER.USER_LOCATION IS '회원지역';
COMMENT ON COLUMN PLAYER.USER_PHONE IS '회원전화번호';
COMMENT ON COLUMN PLAYER.RECORD_ID IS '승패ID';
COMMENT ON COLUMN PLAYER.TEAM1 IS '팀ID';
COMMENT ON COLUMN PLAYER.TEAM1_FLAG IS '0 미승인
1 승인';
COMMENT ON COLUMN PLAYER.TEAM2 IS '팀ID';
COMMENT ON COLUMN RECORD.RECORD_ID IS '승패ID'; 
COMMENT ON COLUMN RECORD.FB_TOTAL IS '축구_토탈';
COMMENT ON COLUMN RECORD.FB_WIN IS '축구_승';
COMMENT ON COLUMN RECORD.FB_DRAW IS '축구_무승부';
COMMENT ON COLUMN RECORD.BB_TOTAL IS '농구_토탈';
COMMENT ON COLUMN RECORD.BB_WIN IS '농구_승';
COMMENT ON COLUMN RECORD.BB_DRAW IS '농구_무승부';
COMMENT ON COLUMN RECORD.PP_TOTAL IS '탁구_토탈';
COMMENT ON COLUMN RECORD.PP_WIN IS '탁구_승';
COMMENT ON COLUMN RECORD.PP__DRAW IS '탁구_무승부';
COMMENT ON COLUMN RECORD.BL_TOTAL IS '볼링_전체';
COMMENT ON COLUMN RECORD.BL_WIN IS '볼링_승';
COMMENT ON COLUMN RECORD.BL_DRAW IS '볼링_무승부';
COMMENT ON COLUMN REPLY.USER_ID IS '회원ID';
COMMENT ON COLUMN TEAM.TEAM_ID IS '팀ID';
COMMENT ON COLUMN TEAM.TEAM_NAME IS '팀이름';
COMMENT ON COLUMN TEAM.TEAM_SCORE IS '팀승점';
COMMENT ON COLUMN TEAM.TEAM_MANNER IS '팀매너점수';
COMMENT ON COLUMN TEAM.TEAM_GAMETYPE IS '팀종목';
COMMENT ON COLUMN TEAM.TEAM_OPEN IS '팀 모집여부';

